# Generated by Django 5.2.6 on 2025-09-13 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.IntegerField(primary_key=True, serialize=False)),
                ('car_brand', models.CharField(max_length=100)),
                ('car_model', models.CharField(max_length=100)),
                ('year', models.DateField()),
                ('car_price', models.IntegerField()),
                ('car_color', models.CharField(max_length=100)),
            ],
        ),
    ]
